- name: Copy rabbitmq config file
  ansible.builtin.template:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo


- name: Installing Rabbitmq
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: latest

- name: Starting Rabbitmq
  ansible.builtin.systemd_service:
    name: rabbitmq-server
    state: restarted
    enabled: true

- name: Setting Rabbitmq permissions
  ansible.builtin.shell: rabbitmqctl add_user {{ secrets.AMQP_USER}} {{ secrets.AMQP_PASS }} ; rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"

  #PASSWORDS COMES FROM VAULT