- name: Adding Roboshop user
  ansible.builtin.user:
    name: roboshop

- name: Remove the default content that serving.
  ansible.builtin.file:
    path: "{{ app_path }}"
    state: absent

- name: Creating app directory
  ansible.builtin.file:
    path: "{{ app_path }}"
    state: directory

#- name: Download the frontend content
#  ansible.builtin.get_url:
#    url: https://roboshop-artifacts.s3.amazonaws.com/{{component}}-v3.zip
#    dest: /tmp/{{component}}.zip


#Download frontend code and extract zip file ansible module
- name: Download code and extract zip file ansible module
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}-v3.zip
    dest: "{{ app_path }}"
    remote_src: yes