- name: Installing Golang
  ansible.builtin.dnf:
    name:
      - golang

#get a task from another role
- name: App Pre-req -Run tasks/other.yaml instead of 'main'
  ansible.builtin.include_role:
    name: common
    tasks_from: app-prereq

- name: Download App dependencies
  ansible.builtin.shell: go mod init dispatch ; go get ; go build
  args:
    chdir: "{{ app_path }}" # go inside app path and run npm install


- name: Load schema -copy-mysql file-mysql client
  ansible.builtin.include_role:
    name: common
    tasks_from: schema
  when: schema_setup is defined

#get a task from another role
- name: SystemD service
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd

