#ansible group task with block, on top block apply condition
- name: Load mongodb schema
  when: schema_setup == "mongo"
  block:
    - name: Copy MongoDB repo file
      ansible.builtin.template:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install MongoDB Client
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: latest

    - name: Load Master Data
      ansible.builtin.shell:  mongosh --host mongo.{{ env }}.meppk.xyz </app/db/{{ item }}.js
      loop: "{{schema_files}}"

- name: Load mysql schema
  when: schema_setup == "mysql"
  block:
    - name: Install mysql client
      ansible.builtin.dnf:
        name: mysql
        state: latest

    - name: Load master data
      ansible.builtin.shell:  mysql -h mysql.{{ env }}.meppk.xyz -uroot -p{{ secrets.MYSQL_ROOT_PASSWORD }} < /app/db/{{ item }}.sql
      loop: "{{schema_files}}"
    #






#  for file in schema master-data app-user; do
#  echo Loading  file is - $file.sql
#  mysql -h mysql.dev.meppk.xyz -uroot -pRoboShop@1 < /app/db/$file.sql &>>$LOG_FILE
#  if [ $? -eq 0 ]; then
#  echo -e "\e[32mSUCCESS\e[0m"
#  else
#  echo -e "\e[31mFAILURE---exit 1ing\e[0m"
#  exit 1
#  fi
#  done
#
