#copy mongo client repo file
- name: copy {{ component}} service file
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest: /etc/systemd/system/{{ component }}.service

- name: Start {{ component}}  Service
  ansible.builtin.systemd_service:
    state: restarted
    name: "{{ component}}"
    enabled: true
    daemon-reload: true