- name: Installing MySQLserver
  ansible.builtin.dnf:
    name: mysql-server

- name: Starting MySQLserver
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: yes

- name: Setting MySQLserver new password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ secrets.MYSQL_ROOT_PASSWORD }}
  #password comes from vault
