
#dnf install docker -y
#docker run -d -p 8080:8080 -e CATALOGUE_HOST=catalogue-ip -e CATALOGUE_PORT=8080 -e REDIS_HOST=redis-ip public.ecr.aws/w8x4g9h7/roboshop-v3/cart

  -  name: Run shipping container
     containers.podman.podman.container:
       name: dispatch
       image: public.ecr.aws/w8x4g9h7/roboshop-v3/shipping
       state: started
       ports:
         - "8080:8080"
       env:
          CART_ENDPOINT="{{ secrets.CART_ENDPOINT }}"
          DB_HOST="{{ secrets.DB_HOST }}"

  - name: Load schema container
    loop:
      - app-user
      - schema
      - master-data
    containers.podman.podman.container:
      name: "{{ item }}"
      image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
      state: started
      ports:
        - "8080:8080"
      env:
        DB_TYPE= "{{ secrets.DB_TYPE }}"
        APP_GIT_URL= "{{ secrets.APP_GIT_URL }}"
        DB_HOST= "{{ secrets.DB_HOST }}"
        DB_USER= "{{ secrets.DB_USER }}"
        DB_PASS= "{{ secrets.DB_PASS }}"
        SCHEMA_FILE= "db/{{ item }}.sql"



